<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->getTitle()?></title>
		<link rel="icon" href="favicon.ico">
		<link rel="stylesheet" href="http://localhost:8005/template/assets/style.css">
		<?=$this->getBlockContent('header-style')?>
		<script>
			var $ui = {};
		</script>
		<?=$this->getBlockContent('header-script')?>
	</head>

	<body>
		<header>
			Header
		</header>
		<main>
			<div>
				<img src="<?=$this->getAssetUrl('assets/sampleimage.svg')?>" alt="sample image">
			</div>
			<div style="border: 1px solid black">
				<?=$this->getMainContent()?>
			</div>
		</main>
		<footer>
			Footer
		</footer>
	</body>	
	<?=$this->getBlockContent('footer-script')?>
</body>