services:
  <?=$DATA['containername']?>:
    container_name: <?=$DATA['containername']?> 
    image: webserver_8_3
    hostname: <?=$DATA['containername']?> 
    ports:
      - <?=$DATA['port']?>:80
    networks:
      - <?=$DATA['network']?> 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CONFIG=config-development.php
      - DEBUG=true
    volumes:
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./webserver.conf:/etc/apache2/sites-available/webserver.conf
<?php 
	  if ($DATA['webservice_dev_mode']==true) {
		  echo "      - ./../../../agungdhewe/webservice:/home/agung/Development/agungdhewe/webservice:consistent\n";
	  }		  
?>      - ./../:<?=$DATA['dir']?>:consistent
    working_dir: <?=$DATA['dir']?> 

networks:
  devnetwork:
    name: <?=$DATA['network']?> 
    external: true




