#!/bin/bash


echo Reset Installasi

# Hapus .vscode
rm -rf ./.vscode
rm -rf ./dockerbuild
rm -rf ./template
rm -rf ./pages
rm -rf ./contents
rm -f ./.gitignore
rm -f ./.htaccess
rm -f ./config.php
rm -f ./config-development.php
rm -f ./debug-monitor.sh
rm -f ./debug.txt
rm -f ./favicon.ico
rm -f ./*.code-workspace
rm -f ./index.php
rm -f ./log.txt
rm -f ./testurl.sh
rm -f ./docker-up.sh
rm -f ./docker-down.sh
rm -f ./docker-cli.sh