<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot <?=$DATA['dir']?>  

    <Directory <?=$DATA['dir']?>>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride all
                Order allow,deny
                Require all granted
                Allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>